stages:
  - build
  - deploy

variables:
  IMAGE_NAME: "nginx-image"
  DOCKER_REGISTRY_IMAGE: $DOCKER_USERNAME/$IMAGE_NAME
  DOCKER_IMAGE_TAG: $CI_COMMIT_TAG

image: docker:latest
services:
  - docker:dind

build:
  stage: build
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_ACCESS_TOKEN
    - docker pull $DOCKER_REGISTRY_IMAGE:latest || true
    - >
      docker build
      --pull
      --cache-from $DOCKER_REGISTRY_IMAGE:latest
      --label "org.opencontainers.image.title=$CI_PROJECT_TITLE"
      --label "org.opencontainers.image.url=$CI_PROJECT_URL"
      --label "org.opencontainers.image.created=$CI_JOB_STARTED_AT"
      --label "org.opencontainers.image.revision=$CI_COMMIT_SHA"
      --label "org.opencontainers.image.version=$CI_COMMIT_REF_NAME"
      --tag $DOCKER_REGISTRY_IMAGE:$CI_COMMIT_TAG
      .
    - docker tag $DOCKER_REGISTRY_IMAGE:$CI_COMMIT_TAG $DOCKER_REGISTRY_IMAGE:latest
    - docker push $DOCKER_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - docker push $DOCKER_REGISTRY_IMAGE:latest

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    # Логин в Docker registry
    - docker login -u $DOCKER_USERNAME -p $DOCKER_ACCESS_TOKEN
    - docker pull $DOCKER_REGISTRY_IMAGE:$CI_COMMIT_TAG || true
    - kubectl apply -f k8s/nginx-deployment.yml  # Применяем деплой
  only:
    - tags  # Деплой только для тегов
