stages:
  - build
  - deploy

variables:
  IMAGE_NAME: "nginx-image"
  DOCKER_IMAGE_TAG: $DOCKER_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  DOCKER_REGISTRY_IMAGE: $DOCKER_USERNAME/$IMAGE_NAME

image: docker:latest
services:
  - docker:dind

Build:
  stage: build
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_ACCESS_TOKEN
    - docker pull $DOCKER_REGISTRY_IMAGE:latest || true
    - >
      docker build
      --pull
      --cache-from $DOCKER_REGISTRY_IMAGE:latest
      --label "org.opencontainers.image.title=$CI_PROJECT_TITLE"
      --label "org.opencontainers.image.url=$CI_PROJECT_URL"
      --label "org.opencontainers.image.created=$CI_JOB_STARTED_AT"
      --label "org.opencontainers.image.revision=$CI_COMMIT_SHA"
      --label "org.opencontainers.image.version=$CI_COMMIT_REF_NAME"
      --tag $DOCKER_IMAGE_TAG
      .
    # Установка тега для ветки или коммита, если `CI_COMMIT_TAG` пуст
    - if [ -n "$CI_COMMIT_TAG" ]; then
        docker tag $DOCKER_IMAGE_TAG $DOCKER_REGISTRY_IMAGE:$CI_COMMIT_TAG;
      else
        docker tag $DOCKER_IMAGE_TAG $DOCKER_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME;
      fi
    - docker push $DOCKER_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

  only:
    - main
  tags:
    - my-runner-tag
  
deploy-to-k8s:
  stage: deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: [""] 
  script:
    - kubectl apply -f deployment.yaml
  rules:
    - if: $CI_COMMIT_TAG
  tags:
    - my-runner-tag
