stages:
  - build
  - deploy

variables:
  IMAGE_NAME: "nginx-image"
  DOCKER_REGISTRY_IMAGE: $DOCKER_USERNAME/$IMAGE_NAME
  DOCKER_IMAGE_TAG: $CI_COMMIT_SHORT_SHA  

image: docker:latest
services:
  - docker:dind

build:
  stage: build
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_ACCESS_TOKEN
    - docker pull $DOCKER_REGISTRY_IMAGE:latest || true
    - echo "Building image with tag: $DOCKER_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"
    - docker build --no-cache -t "$DOCKER_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA" .
    - docker run --rm "$DOCKER_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA" ls /usr/share/nginx/html  # Проверка содержимого
    - docker tag "$DOCKER_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA" "$DOCKER_REGISTRY_IMAGE:latest"
    - docker push "$DOCKER_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"
    - docker push "$DOCKER_REGISTRY_IMAGE:latest"
  only:
    - main
  tags:
    - my-runner-tag

deploy:
  stage: deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: [""] 
  script:
    - export IMAGE_TAG="$DOCKER_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"  # Определяем текущий тег образа
    - echo "Deploying image $IMAGE_TAG"
    # Подставляем тег в файл deployment.yml
    - sed -i "s|image: .*$|image: $IMAGE_TAG|" deployment.yml
    - kubectl apply -f deployment.yaml  
  only:
    - tags  
    - main
  when: manual
  tags:
    - my-runner-tag
