stages:
  - build
  - deploy

variables:
  IMAGE_NAME: "nginx-image"
  DOCKER_REGISTRY_IMAGE: $DOCKER_USERNAME/$IMAGE_NAME
  DOCKER_IMAGE_TAG: $CI_COMMIT_TAG

image: docker:latest
services:
  - docker:dind

build:
  stage: build
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_ACCESS_TOKEN
    - docker build -t ""$DOCKER_IMAGE_NAME"" ./docker
    - docker push "$DOCKER_IMAGE_NAME"
  only:
    - main
  tags:
    - my-runner-tag

    

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - kubectl apply -f deployment.yml 
  only:
    - tags  # Деплой только для тегов
  tags:
    - my-runner-tag

