stages:
  - build
  - deploy

variables:
  IMAGE_NAME: "nginx-image"
  DOCKER_REGISTRY_IMAGE: $DOCKER_USERNAME/$IMAGE_NAME
  # DOCKER_IMAGE_TAG: ${CI_COMMIT_TAG:-$CI_COMMIT_SHORT_SHA}   

image: docker:latest
services:
  - docker:dind

build:
  stage: build
  script:
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_ACCESS_TOKEN"
    - |
      if [ -z "$CI_COMMIT_TAG" ]; then
        DOCKER_IMAGE_TAG=$CI_COMMIT_SHORT_SHA
      else
        DOCKER_IMAGE_TAG=$CI_COMMIT_TAG
      fi
    - docker build --no-cache -t "${DOCKER_REGISTRY_IMAGE}:${DOCKER_IMAGE_TAG}" .
    - docker push "${DOCKER_REGISTRY_IMAGE}:${DOCKER_IMAGE_TAG}"
  only:
    - main
    - tags
  tags:
    - my-runner-tag

deploy:
  stage: deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: [""]
  needs:
    - build
  script:
    - export DOCKER_REGISTRY_IMAGE="${DOCKER_USERNAME}/nginx-image"
    - export DOCKER_IMAGE_TAG="${CI_COMMIT_TAG:-$CI_COMMIT_SHORT_SHA}"
    - envsubst < deployment.yaml | kubectl apply -f -
  only:
    - tags
  tags:
    - my-runner-tag
