stages:
  - build
  - deploy

variables:
  IMAGE_NAME: "nginx-image"
  DOCKER_REGISTRY_IMAGE: $DOCKER_USERNAME/$IMAGE_NAME
  DOCKER_IMAGE_TAG: $CI_COMMIT_SHORT_SHA  

image: docker:latest
services:
  - docker:dind

build:
  stage: build
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_ACCESS_TOKEN
    - docker pull $DOCKER_REGISTRY_IMAGE:latest || true
    - docker build -t "$DOCKER_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA" .
    - docker tag "$DOCKER_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA" "$DOCKER_REGISTRY_IMAGE:latest"  
    - docker push "$DOCKER_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"
    - docker push "$DOCKER_REGISTRY_IMAGE:latest"
  only:
    - main
  tags:
    - my-runner-tag

deploy:
  stage: deploy
  script:
    - kubectl apply -f deployment.yml  
  only:
    - tags  
    - main
  when: manual
  tags:
    - my-runner-tag
