stages:
  - build
  - deploy

variables:
  IMAGE_NAME: "nginx-image"
  DOCKER_REGISTRY_IMAGE: $DOCKER_USERNAME/$IMAGE_NAME
  DOCKER_IMAGE_TAG: ${CI_COMMIT_TAG:-latest}  # Используем тег commit или latest по умолчанию

image: docker:latest
services:
  - docker:dind

# Стадия сборки
build:
  stage: build
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_ACCESS_TOKEN
    - docker pull $DOCKER_REGISTRY_IMAGE:latest || true
    - >
      docker buildx build
      --pull
      --cache-from $DOCKER_REGISTRY_IMAGE:latest
      --label "org.opencontainers.image.title=$CI_PROJECT_TITLE"
      --label "org.opencontainers.image.url=$CI_PROJECT_URL"
      --label "org.opencontainers.image.created=$CI_JOB_STARTED_AT"
      --label "org.opencontainers.image.revision=$CI_COMMIT_SHA"
      --label "org.opencontainers.image.version=$CI_COMMIT_REF_NAME"
      --tag $DOCKER_REGISTRY_IMAGE:$DOCKER_IMAGE_TAG  # Используем тег из переменной
      .  # Контекст сборки (текущая директория)
    - docker tag $DOCKER_REGISTRY_IMAGE:$DOCKER_IMAGE_TAG $DOCKER_REGISTRY_IMAGE:latest  # Тегируем также как latest
    - docker push $DOCKER_REGISTRY_IMAGE:$DOCKER_IMAGE_TAG
    - docker push $DOCKER_REGISTRY_IMAGE:latest
  only:
    - main
  tags:
    - my-runner-tag


# Стадия деплоя
deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_ACCESS_TOKEN
    - docker pull $DOCKER_REGISTRY_IMAGE:$CI_COMMIT_TAG || true  # Берем образ с тегом коммита или latest
    - kubectl apply -f k8s/nginx-deployment.yml  # Применяем деплой
  only:
    - tags  # Деплой только для тегов
  tags:
    - my-runner-tag
