stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE: "alexandreevich/nginx-image" 

build-image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_ACCESS_TOKEN"
    - docker build -t $DOCKER_IMAGE:latest .
    - docker push $DOCKER_IMAGE:latest

  only:
    - main
  tags:
    - my-runner-tag
  
deploy-to-k8s:
  stage: deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: [""] 
  script:
    - kubectl apply -f k8s/deployment.yaml
    - kubectl apply -f k8s/nginx-service.yml

  tags:
    - my-runner-tag
