apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-static
  namespace: applica
  labels:
    app: nginx-static
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-static
  template:
    metadata:
      labels:
        app: nginx-static
    spec:
      containers:
        - name: nginx
          image: ${DOCKER_REGISTRY_IMAGE}:${DOCKER_IMAGE_TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
