apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-static
  labels:
    app: nginx-static
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-static
  template:
    metadata:
      labels:
        app: nginx-static
    spec:
      containers:
        - name: nginx
          image: $DOCKER_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA" 
          ports:
            - containerPort: 80
